import type { Metadata } from "next"
import { Plus_Jakarta_Sans } from "next/font/google"
import { Providers } from "./providers"

const font = Plus_Jakarta_Sans({
  subsets: ["latin"],
  weight: ["400"],
  // fallback: ["Helvetica", "Arial", "sans-serif"],
})

export const metadata: Metadata = {
  title: "Csma Consult",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={font.className}>
        <Providers>{children}</Providers>
      </body>
    </html>
  )
}
